import 'dart:math';

//this is the code for the affirmation provider functionality
//class containing a list of affirmations to pull from
class AffirmationProvider {
  final List<String> _allAffirmations;
  late List<String> _availableAffirmations;

  AffirmationProvider(this._allAffirmations) {
    _availableAffirmations = List.from(_allAffirmations)..shuffle(Random());
  }

  // Affirmation list to be used by the provider
  factory AffirmationProvider.withDefaultAffirmations() {
    return AffirmationProvider([
      "Asking for help is a sign of self-respect and self-awareness.",
      "Changing my mind is a strength, not a weakness.",
      "Every decision I make is supported by my whole and inarguable experience.",
      "I affirm and encourage others, as I do myself.",
      "I alone hold the truth of who I am.",
      "I am allowed to ask for what I want and what I need.",
      "I am allowed to feel good.",
      "I am capable of balancing ease and effort in my life.",
      "I am complete as I am, others simply support me.",
      "I am content and free from pain.",
      "I am doing the work that works for me.",
      "I am good and getting better.",
      "I am growing and I am going at my own pace.",
      "I am held and supported by those who love me.",
      "I am in charge of how I feel and I choose to feel happy.",
      "I am listening and open to the messages the universe has to offer today.",
      "I am loved and worthy.",
      "I am more than my circumstances dictate.",
      "I am open to healing.",
      "I am optimistic because today is a new day.",
      "I am peaceful and whole.",
      "I am proof enough of who I am and what I deserve.",
      "I am responsible for myself, and I start there.",
      "I am safe and surrounded by love and support.",
      "I am still learning so it's okay to make mistakes.",
      "I am understood and my perspective is important.",
      "I am valued and helpful.",
      "I am well-rested and excited for the day.",
      "I am worthy of investing in myself.",
      "I belong here, and I deserve to take up space.",
      "I breathe in healing, I exhale the painful things that burden my heart.",
      "I breathe in trust, I exhale doubt.",
      "I can be soft in my heart and firm in my boundaries.",
      "I can control how I respond to things that are confronting.",
      "I can hold two opposing feelings at once, it means I am processing.",
      "I celebrate the good qualities in others and myself.",
      "I deserve an affirming touch on my own terms.",
      "I deserve information and I deserve moments of silence, too.",
      "I deserve self-respect and a clean space.",
      "I do all things in love.",
      "I do not have to linger in dark places; there is help for me here.",
      "I do not pretend to be anyone or anything other than who I am.",
      "I do not rise and fall for another.",
      "I do not rush through my life, I temper speed with stillness.",
      "I embrace change seamlessly and rise to the new opportunity it presents.",
      "I embrace the questions in my heart and welcome the answers in their own time.",
      "I grow towards my interests, like a plant reaching for the sun.",
      "I have come farther than I would have ever thought possible, and I'm learning along the way.",
      "I have everything I need to succeed.",
      "I hold community for others, and am held in community by others.",
      "I hold wisdom beyond knowledge.",
      "I invite abundance and a generous heart.",
      "I invite art and music into my life.",
      "I leave room in my life for spontaneity.",
      "I let go of the things that sit achingly out of reach.",
      "I look forward to tomorrow and the opportunities that await me.",
      "I love that I love what I love.",
      "I make decisions based on a good gut, I make changes based on a growing heart.",
      "I make time to experience grief and sadness when necessary.",
      "I nourish myself with kind words and joyful foods.",
      "I practice gratitude for all that I have, and all that is yet to come.",
      "I release the fears that do not serve me.",
      "I respect the cycle of the seasons.",
      "I seek out mystery in the ordinary.",
      "I strive for joy, not for perfection.",
      "I tell the truth about who I am and what I need from others.",
      "I uplift my joy and the joy of others.",
      "I welcome the wisdom that comes with growing older.",
      "I welcome what is, I welcome what comes.",
      "I will allow myself to evolve.",
      "Letting go creates space for opportunities to come.",
      "My body is beautiful in this moment and at its current size.",
      "My body is worthy of being cared for and adorned in beautiful garments.",
      "My feelings deserve names, deserve recognition, deserve to be felt.",
      "My heart is open to helpfulness from myself and from others.",
      "My heart knows its own way.",
      "My life is not a race or competition.",
      "My perspective is unique and important.",
      "My pleasure does not require someone else's pain.",
      "My sensitivity is beautiful, and my feelings and emotions are valid.",
      "My weirdness is wonderful.",
      "Saying 'no' is an act of self-affirmation, too.",
      "Sometimes the work is resting.",
      "There is growth in stillness.",
      "There is peace in changing your mind when it is done in love.",
      "There is poetry in everything, if I look for it.",
      "There is room for me at the table.",
      "There is something in this world that only I can do. That is why I am here.",
      "There is strength in quiet, there is vulnerability in being loud.",
      "Today I celebrate that I am younger than I'm ever going to be.",
      "Today is an opportunity to grow and learn.",
      "When I feel fear, I feed trust.",
      "When I focus on my reason for being, I am infinitely brave.",
      "When I forgive myself, I free myself.",
      "When I release shame, I move into myself more beautifully.",
      "When I root into the earth, the earth rises to support me.",
      "When I speak my needs, I receive them abundantly.",
      "When I talk to myself as I would a friend, I see all my best qualities and I allow myself to shine.",
      "Words may shape me, but they do not make me. I am here already.",
      "I love you more than you will ever know!",
      "I deserve rest and relaxation.",
      "No other person can do it like I can.",
      "I will get to where I want to be. I have to just keep going.",
      "My opinions aren't tattoos. I can change them anytime.",
      "I are not one thing. I am a million amazing things.",
      "Sometimes letting go is the best way to free yourself.",
      "I don't have to be perfect to be amazing.",
      "I don't need permission to say no.",
      "We're all imposters here. Just own it.",
      "That thing you're self-conscious about is what makes you light up the room.",
      "I am in control. I am my own boss.",
      "Don't waste a drop of energy trying to change someone else.",
      "I'm allowed to fail. Get back up, dust myself off, and learn from it.",
      "Change is good. I embrace and welcome it.",
      "You can either worry or believe in yourself. Guess which one feels better.",
      "If it's an 'everything feels so heavy' type of day, that's okay.",
      "The things I say to myself matter. I will be kind to me.",
      "I'm a complete and unique weirdo. It's my superpower.",
      "I've come so far, and I'm still going.",
      "Today, I'm betting on me, and I like the odds.",
      "I send my negative thoughts to stand in the corner for a permanent timeout.",
      "I am one decision away from the life I'm striving toward.",
      "I can recover from anything. My resilience is unmatched.",
      "I share the love I put into the World with myself.",
      "If I can believe in myself, I can do anything.",
      "If I believe in anything, I believe in me.",
      "My pet thinks I'm amazing and they're a really good judge of character.",
      "Blurt out your ideas! Or don't, and watch what doesn't happen.",
      "Even the wildest dreams deserve a chance.",
      "I'll find a way. Or I'll make one.",
      "Take a look around. You do matter. Remember that.",
      "Image how great it will feel when you are done. Now get going!",
      "The greatest of journeys starts with a single step.",
      "Take the time to enjoy all the things you have worked so hard for.",
      "I don't allow worry to make me forget to live.",
      "There's no such thing as 'the right time'. But there is no better time than right now.",
      "I am worthy of everything good in this life.",
      "I choose me. Everytime.",
      "My best is more than enough.",
      "If it won't matter in 10 years. It's not worth the energy to worry about.",
      "Drown out the noise and just keep going.",
      "Don't support anyone who doesn't support you.",
      "Don't take anyone's negativity. You deserve respect, all of the time.",
      "I'm tougher than my toughest day.",
      "If you believe in yourself, others will too.",
      "Don't forget to celebrate the silent battles that you won today.",
      "Flowers grow out of dirt and manure. Blooming, Baby!",
      "Everything I need to get it done is already inside of me.",
      "My ending is unwritten. It's never too late to build the life I deserve.",
      "No one else is dwelling on your mistakes. Neither should you.",
      "I am so proud of how far I've come, and I'm not done yet.",
      "I let no one disturb my peace.",
      "Don't water yourself down for anyone. If you're too much for them, it's their problem.",
      "Don't hold your tears in. Get them out, breathe, and feel better.",
      "My worth is not tied to my productivity.",
    ]);
  }
  //check screen for affirmation
  String getAffirmation() {
    if (_availableAffirmations.isEmpty) {
      _availableAffirmations = List.from(_allAffirmations)..shuffle(Random());
    }

    return _availableAffirmations.removeLast();
  }
}
